console.log('Hi');
setTimeout(function cb1() {
    console.log('cb1');
},0)
console.log('Bye');
console.log('Bye2');
console.log('Bye3');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');
console.log('Bye4');